version: 0.2
run-as: root

phases:
  install:
    commands:
      - curl -o kubectl curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.13/2022-10-31/bin/linux/amd64/kubectl
      - curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.13/2022-10-31/bin/linux/amd64/kubectl.sha256
      - openssl sha1 -sha256 kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - kubectl version --short --client
      - chmod +x prereqs.sh
      - sh prereqs.sh
      - chmod +x create_iam_role.sh
      - sh create_iam_role.sh
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks update-kubeconfig --name angula --region us-east-2 
      - echo check config 
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl get svc
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 928052840712.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Starting The Process
      - npm install -g @angular/cli@latest
      - ng build --base-href=.
      - echo Building a Docker image..
      - docker build -t angular .
      - echo Tagging Docker image for ECR..
      - docker tag angular:latest 928052840712.dkr.ecr.us-east-2.amazonaws.com/angular:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker Image
      - docker push 928052840712.dkr.ecr.us-east-2.amazonaws.com/angular:latest
      - echo DONE
      - kubectl apply -f deployment.yaml
      - kubectl rollout restart -f deployment.yaml
      - printf '[{"name":"angular","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/angular:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
