version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --base-href=.
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
