apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: app
  annotations:
    fluxcd.io/automated: "true"  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: 928052840712.dkr.ecr.us-east-2.amazonaws.com/angular:latest
