apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: angular
    app.kubernetes.io/version: '1.0.0'
    app.kubernetes.io/managed-by: kubectl
  name: angular
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - image: 928052840712.dkr.ecr.us-east-2.amazonaws.com/angular:latest
          imagePullPolicy: Always
          name: angular
          ports:
            - containerPort: 3000
