apiVersion: v1
kind: Service
metadata:
  name: angular
  namespace: angular
  labels:
    app: angular
spec:
  selector:
    app: angular
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
